### ISSUE TITLE
[FR] Option to not open the "Output" panel on error

### ISSUE THREAD

**Issue by wenfangdu** [mark-wiemer-org/ahkpp#103] opened 2021-08-28 13:20 UTC
When encountering a runtime error, the error message box is sufficient, would be nice to have an option to not open the "Output" panel on error.

**Comment by mark-wiemer** [comment] 2023-01-31 02:58
Similar to #70

**Comment by mark-wiemer** [comment] 2023-06-21 02:09
Closing as dupe of #70

**Closed by mark-wiemer** 2023-06-21 02:09 UTC
Labels: enhancement, debugger
