### ISSUE TITLE
Output window automatically opens up each time a script is run 

### ISSUE THREAD

**Issue by Wilson703** [mark-wiemer-org/ahkpp#492] opened 2024-09-02 11:41 UTC
## Description

When selecting to run an AHK file, the extension sends information to the output window making it pop up each time, 

## Reproduction steps

Run any script. AHK v1

## Expected behavior

Default behavior expected is that the script will not push messages to the output opening it each time, It might be valuable as a setting to turn on, but by default it causes this to pop up each time taking screen space without the ability to close it as it will just pop up the second you rerun the script.

**Comment by fade2gray** [comment] 2024-09-02 12:25
This old request never actually got implemented - #70 😞

**Comment by mark-wiemer** [comment] 2024-09-02 16:21
Never, or not yet? 😉 Closing this as a dupe of #70, please follow that incident for updates

**Comment by Wilson703** [comment] 2024-09-02 18:29
Actually, that's not the same. This bug was introduced in version 6, and it adds even more messages to the output. Previous versions only added some types of errors to it hence it was rarely opened. Now it also includes the amount of time it took the script to load, ID etc. which opens it each time a script is run. 

Version 5 is good enough for what I need now. It's way too annoying to constantly have to close that output window, And there doesn't seem to be any way to stop that behavior from VS code. It is extension specific

**Comment by mark-wiemer** [comment] 2024-09-02 19:41
Thanks for the comments. Turns out I've never noticed these behaviors because I always have the output window open when developing! This is at the top of the backlog :)

**Comment by Wilson703** [comment] 2024-09-03 05:57
Awesome, thanks 🫡
From my end, my screen resolution is not high enough to have comfortable access to the code when the output is open. It simply eats up even more of the little space there is, so leaving it open with be me seeing the code one line at a time 😂

**Closed** 2024-09-19 03:49 UTC
Labels: enhancement, debugger
