### ISSUE TITLE
Wrong indentation when moving line of code out of if-statement

### ISSUE THREAD

**Issue by helperman** [mark-wiemer-org/ahkpp#403] opened 2023-08-25 12:26 UTC
## Description

There are few issues:
1. Wrong indentation happens of a moved line of code when moving line of code out of if-statement.
2. Wrong indentation happens of a surrounded code (if-statement itself become without indentation)

## Reproduction steps

Use "move line up"-hotkey to move line out of if-statement:
![0000000314](https://github.com/mark-wiemer-org/ahkpp/assets/8351863/f0e88685-2718-4103-952d-c2ea5556a4a1)

## Expected behavior

The moved statement should keep the same indentation as if-statement.
The if-statement should not change it's indentation.

## Actual behavior

The moved statement has no indentation when moved before if-statement.
The if-statement has no indentation after moving a line inside a body of if-statement.

**Comment by kyklish** [comment] 2023-08-26 14:13
Similar with #313

**Comment by mark-wiemer** [comment] 2023-08-27 23:34
Thanks for reporting, I'll track this as a duplicate of #319--this will be fixed when that one is.

**Closed by mark-wiemer** 2023-08-27 23:34 UTC
Labels: bug
