### ISSUE TITLE
go to defintion. not working

### ISSUE THREAD

**Issue by Doaexpert** [mark-wiemer-org/ahkpp#561] opened 2024-11-06 00:36 UTC
## Description

go to definition is not working anymore with the latest updates

## Reproduction steps

gosub, definition
press f12, not working

## Expected behavior

open de ahk file where the definiton is.

## Additional context

Add any other context about the problem here, including screenshots. If no context is needed, please remove this section.

**Comment by mark-wiemer** [comment] 2024-11-08 02:04
Dupe of #559, will be fixed in this weekend's release

**Closed by mark-wiemer** 2024-11-08 02:04 UTC
Labels: bug
