### ISSUE TITLE
Code coloring issue with VSCode Theme: Dark (Visual Studio)

### ISSUE THREAD

**Issue by homezonebenny** [mark-wiemer-org/ahkpp#501] opened 2024-09-16 06:53 UTC
There's an issue with the VSCode Theme:
_"Dark (Visual Studio)"_
and your **AutoHotkey Plus Plus** extension.

**The coloring is messed up:**

![image](https://github.com/user-attachments/assets/c5ca42d2-ee51-4f19-9737-656de4926d3b)

**When I switch the theme to the new "Dark Modern" then it seems working:**

![image](https://github.com/user-attachments/assets/fa2d56d1-61d8-4da7-9002-6a3bed5c701d)

So that's the issue I want to report. :-)
I hope this information helps to address the problem.

**The red one is the bugged one, **but** green one works, and it's the same color theme like the red one:**

![image](https://github.com/user-attachments/assets/9e7bb1fa-e69e-4ffa-a74d-8875da8e78bf)

So I "fixed" the bug for me, but still this should be adressed somehow, but maybe it's for the VSCode Developer team directly, not for your plugin.

**Comment by fade2gray** [comment] 2024-09-16 15:41
How I see it ...

![Screenshot 2024-09-16 163645](https://github.com/user-attachments/assets/ed36cfc4-5614-47e1-a91f-254e704f0465)

**Comment by homezonebenny** [comment] 2024-09-16 18:15
@fade2gray 
That's interessting!
I saw on your screenshot that you use the new Dark Theme and instantly tested it if this is the solution and it was.


@mark-wiemer 
It looks like that the code coloring have a bug when you are using the "old" VSCode Theme "Dark (Visual Studio)".

**When I switch the theme to the new "Dark Modern" then it seems working:**

![image](https://github.com/user-attachments/assets/fa2d56d1-61d8-4da7-9002-6a3bed5c701d)

So that's the issue I want to report. :-)
I can't edit the original post anymore, but I hope this information helps to adress the problem.


**The red one is the bugged one, **but** green one works, and it's the same color theme like the red one:**

![image](https://github.com/user-attachments/assets/9e7bb1fa-e69e-4ffa-a74d-8875da8e78bf)

So I "fixed" the bug for me, but still this should be adressed somehow, but maybe it's for the VSCode Developer team directly, not for your plugin.

**Comment by mark-wiemer** [comment] 2024-09-17 03:58
@homezonebenny This is a feature, not a bug ;)

In the default Visual Studio Dark theme, function names are white by design. You can see the same behavior in TypeScript:
```ts
export function deactivate() {
	return client?.stop();
}

function decode(buf: Buffer) {
	for (const td of textdecoders) {
		try {
			return td.decode(buf);
		} catch { };
	}
	return buf.toString();
}
```

Visual Studio Dark (not recommended by me):

![image](https://github.com/user-attachments/assets/8021f887-5fc2-408e-8b8c-8480b6cafeb9)


Default Dark+ (recommended by me):

![image](https://github.com/user-attachments/assets/af18c004-cbb1-492a-bcfb-219fbabac9ef)

---

Closing as out of scope, please review issues in the VS Code repo itself to see if this is tracked work, but I'd recommend simply using Dark+ :)

**Closed by mark-wiemer** 2024-09-17 03:58 UTC
Labels: bug, syntax highlighter
