### ISSUE TITLE
"Go to Definition" finds the function in a script different than the one you're currently working on

### ISSUE THREAD

**Issue by kyklish** [mark-wiemer-org/ahkpp#338] opened 2023-01-31 08:06 UTC
Sometimes when you hit `Go to Definition`  it finds the function in a script different than the one you're currently working on.
It's boring, would like to disable the search of `Goto to Definition` on different files.
Appreciate any help on it.

_Originally posted by @pepeu93 in https://github.com/vscode-autohotkey/ahkpp/issues/117#issuecomment-1008308270_

**Comment by mark-wiemer** [comment] 2024-10-18 03:41
closing as a dupe of #205

**Closed by mark-wiemer** 2024-10-18 03:41 UTC
Labels: bug, intellisense
