### ISSUE TITLE
"Go to definition" using Ctrl + Click jumps to another file opened in editor / or doesn't jump to definition at all within the same file if the file is very long ~10k lines

### ISSUE THREAD

**Issue by helperman** [mark-wiemer-org/ahkpp#402] opened 2023-08-23 20:21 UTC
Can't provide you with my script since it contains a lot of stupid code :) and sensitive data.
It is not reproducible on small examples (but maybe I'll add more info later).
Recommend you keep an eye on this feature on long scripts.
Ctrl Click doesn't do anything or jumps to the function with the same name in another file which is not even included/linked with each other (maybe it's a feature though?).
For Ahk1.

**Comment by mark-wiemer** [comment] 2023-08-23 23:14
Duplicate of #117, please adjust your maximum parse length setting :)

**Closed by mark-wiemer** 2023-08-23 23:14 UTC
Labels: bug
