### ISSUE TITLE
Why IntelliSense offers things from not included files?

### ISSUE THREAD

**Issue by Gh0sTG0** [mark-wiemer-org/ahkpp#352] opened 2023-03-20 11:04 UTC
## Description

Hi.
Looks like it's some bug (feature? if feature then how turn it off?) with that `IntelliSense` somehow analyzes all files in folder and subfolders, and tries to give me things from other files ignoring if they are included or not.
I have only this thing activated. No other extensions active.

For example, when I'm trying to `IntelliSense` `MsgBox`, it shows me big list of functions with one that will add `MsgBox(msg)` (red pointer on pic) if pressed on top of lists. Correct `msgbox, ...` (green pointer) is somewhere close to bottom.

I'm not sure from where exact `MsgBox()` function is, but I see some number of functions from `\MsgBox2_AHK\AHK1\TheArkive_MsgBox2_Example.ahk` file, like `MsgBox2ExClose(hwnd)` (can be seen on pic, 2nd right after `msgbox()` one), so I'm going to use this one as an example.

I tried to work in new completely empty folder with only one file that is I'm working in and that thing not appears, only correct ones are shown there.

## Reproduction steps

1. In opened folder I have an empty `.ahk` file. In this file I will try to `msgbox`.
2. Plus I have some number of other files, including `\MsgBox2_AHK\AHK1\TheArkive_MsgBox2_Example.ahk` file. `TheArkive_MsgBox2_Example` file is **NOT** `#include` into opened .ahk file, it's completely empty.
3. Try to start writing `ms`
4. See that for some reasons IntelliSense shows you things that are in one folder, but not included in current file.

## Expected behavior

I expect, that only base ahk + opened file's content + `#include`'s will be shown in IntelliSense offers.

## Additional context

![image](https://user-images.githubusercontent.com/13123855/226307479-c6741423-e263-44c9-85c1-0dafcc8bfaa1.png)

PS Just to make things clear: ~95% of my .ahk scripts are small one-file projects, that not need to be allocated to a separate project-folder, that's why they are in one big folder that contains things that can be not included in current one.

**Comment by mark-wiemer** [comment] 2023-03-22 03:30
Yes, this is a long-standing issue, thanks for pointing it out. It's closely related to #338 and likely some other open issues.

**Comment by Gh0sTG0** [comment] 2023-03-22 07:05
> Yes, this is a long-standing issue, thanks for pointing it out. It's closely related to #338 and likely some other open issues.

Thanks for your answer. Hope that can be fixed without rewriting all intellisence function =)

**Comment by mark-wiemer** [comment] 2024-10-18 03:42
Closing as a dupe of #205

**Closed by mark-wiemer** 2024-10-18 03:42 UTC
Labels: bug, intellisense
