### ISSUE TITLE
Turn off error notifications on macOS

### ISSUE THREAD

**Issue by wenfangdu** [mark-wiemer-org/ahkpp#555] opened 2024-10-31 13:08 UTC
Previously on Windows, I wrote a lot of ahk scripts, when viewing them on macOS, ahk++ sends error notification:
<img width="609" alt="image" src="https://github.com/user-attachments/assets/7f36ffbc-d23b-466e-b7ee-74f53c82fbd9">
I need mostly syntax highlighting on macOS with ahk++, constantly sending error popups makes it unusable.
A better way is to send error notifications when actually running the scripts on macOS not when viewing them.

**Comment by mark-wiemer** [comment] 2024-10-31 19:27
Good catch, I should be able to push a quick fix here before my vacation next month :)

**Comment by mark-wiemer** [comment] 2024-11-02 15:46
Closing as a duplicate of #493

**Closed by mark-wiemer** 2024-11-02 15:46 UTC
