### ISSUE TITLE
Temporary freezes in VSC when AHK PP extension enabled

### ISSUE THREAD

**Issue by jb261** [mark-wiemer-org/ahkpp#475] opened 2024-08-23 12:18 UTC
When I have AHK PP extension enabled, I sometimes get temporary freezes of VS Code, where VSC is unresponsive to most attempts to interact with the app, except for closing the app. When it occurs, this temp freeze will usually last 1-3 minutes, then it will be fine for a couple of minutes, the temp freeze again. Disabling AHK PP extension resolves this. 

First encountered this issue a couple of months ago. AHK PP last version used is 5.0.7

VSC info:
Version: 1.89.1 (user setup)
Date: 2024-05-07T05:13:33.891Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by mark-wiemer** [comment] 2024-08-23 13:21
Hi @jb261, do you have very large folders that you're working on, with many AHK files? My first thought is that the extension is trying to parse all your AHK files at once. Does this usually happen when you start up VS Code or in the middle of sessions?

**Comment by jb261** [comment] 2024-08-23 15:27
> Hi @jb261, do you have very large folders that you're working on, with many AHK files? My first thought is that the extension is trying to parse all your AHK files at once. Does this usually happen when you start up VS Code or in the middle of sessions?

No, the folders don't contain many AHK files (though subfolders do). Usually happens in the middle of sessions, but once it starts, it often continues after restarting VS Code. Sometimes I'll go a couple of weeks without this freeze, so it's very intermittent. I usually enable the AHK PP extension because it's so useful, and then once this freeze starts, I'll disable it for a while.

**Comment by fade2gray** [comment] 2024-08-23 16:10
I have 47 extension installed, 10 of which are disabled. The .RUN extension is in my disabled lot, and the rest of your listed extensions are amongst my 37 enabled ones - I have many workspaces with multiple folders, some with many largish scripts, and suffer no freezes.

I wonder if disabling .RUN my fix your freeze - I daren't risk enabling it at this point in case I jinx myself. 😟

**Comment by jb261** [comment] 2024-08-23 16:22
> I have 47 extension installed, 10 of which are disabled. The .RUN extension is in my disabled lot, and the rest of your listed extensions are amongst my 37 enabled ones - I have many workspaces with multiple folders, some with many largish scripts, and suffer no freezes.
> 
> I wonder if disabling .RUN my fix your freeze - I daren't risk enabling it at this point in case I jinx myself. 😟
> 
> Currently running AutoHotkey Plus Plus v5.1.0 (pre-release)

I'll try it!

**Comment by mark-wiemer** [comment] 2024-08-23 18:02
Good idea, there's also [Resolving extension issues with bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) if other folks have the same issue but different extensions installed :)

**Comment by mark-wiemer** [comment] 2024-08-30 02:05
Hey @jb261, unfortunately I can't resolve this without more details--namely, a way to reproduce on my side. As this doesn't seem to be caused by my extension alone, closing as out of scope for now. Feel free to re-open if you have more to share :)

**Closed by mark-wiemer** 2024-08-30 02:05 UTC
Labels: bug, out of scope, question

**Comment by jb261** [comment] 2024-08-30 18:42
Yep, understood. Haven't experienced the issue since disabling the Code Runner extension as @fade2gray suggested. So that may well have been the problem.
